#!/bin/bash

# Setup script for Cloudflare Pages environment variables and bindings

PROJECT_NAME="financial-calculator"
ACCOUNT_ID="c1f6d122a8c3ac94eba60bec3e348b33"
PASSWORD="htSEfMBUBnYm0eqmO4sX6Hxg"

echo "Setting up Cloudflare Pages configuration..."
echo ""
echo "⚠️  This script requires manual setup in the Cloudflare dashboard."
echo ""
echo "Please follow these steps:"
echo ""
echo "1. Set Environment Variable:"
echo "   - Go to: https://dash.cloudflare.com/$ACCOUNT_ID/pages/view/$PROJECT_NAME/settings/environment-variables"
echo "   - Click 'Add variable'"
echo "   - Variable name: ADMIN_PASSWORD"
echo "   - Value: $PASSWORD"
echo "   - Environment: Production (check the box)"
echo "   - Click 'Save'"
echo ""
echo "2. Add D1 Database Binding:"
echo "   - Go to: https://dash.cloudflare.com/$ACCOUNT_ID/pages/view/$PROJECT_NAME/settings/bindings"
echo "   - Scroll to 'D1 database bindings'"
echo "   - Click 'Add binding'"
echo "   - Variable name: DB"
echo "   - D1 database: financial-calculators-db"
echo "   - Click 'Save'"
echo ""
echo "3. Redeploy:"
echo "   - Go to: https://dash.cloudflare.com/$ACCOUNT_ID/pages/view/$PROJECT_NAME"
echo "   - Click 'Deployments' tab"
echo "   - Click 'Retry deployment' on the latest deployment"
echo ""
echo "Once completed, your admin login will work at https://calc.msei.dev/admin"
